import json
import os
from urllib.parse import urlparse

class TrackerLensAnalyzer:
    def __init__(self):
        # Local signatures database to classify known trackers (Module 7 integration)
        self.tracker_signatures = {
            "analytics": ["google-analytics.com", "analytics.google.com", "hotjar.com", "mixpanel.com", "amplitude.com"],
            "advertising": ["doubleclick.net", "googlesyndication.com", "adnxs.com", "criteo.com", "pubmatic.com", "rubiconproject.com"],
            "social": ["facebook.net", "connect.facebook.net", "platform.twitter.com", "linkedin.com/analytics"],
        }

    def extract_domain(self, url):
        """Extracts the primary network domain from a full URL string (Module 6 integration)."""
        try:
            parsed_url = urlparse(url)
            return parsed_url.netloc
        except Exception:
            return ""

    def get_base_domain(self, domain):
        """Simplifies subdomains for a cleaner matching evaluation (e.g., api.google-analytics.com -> google-analytics.com)."""
        parts = domain.split('.')
        if len(parts) > 2:
            return ".".join(parts[-2:])
        return domain

    def classify_domain(self, domain, base_site_domain):
        """Classifies if a domain belongs to the target host website or an external tracking service (Module 7 integration)."""
        base_domain = self.get_base_domain(domain)
        base_target = self.get_base_domain(base_site_domain)
        
        # If the domain matches the visited target site, it is marked as First-Party
        if base_domain == base_target or base_domain in base_target:
            return "First-Party (Essential/Contextual)"
        
        # Check against our local tracking signature database
        for category, signatures in self.tracker_signatures.items():
            for sig in signatures:
                if sig in domain:
                    return f"Third-Party Tracker ({category.capitalize()})"
        
        return "Third-Party (Unclassified/Other CDN)"

    def analyze_har(self, har_file_path):
        """Parses and processes network request log files in HAR format generated by Browser DevTools (Module 5 & 6 integration)."""
        if not os.path.exists(har_file_path):
            print(f"[Error] The file '{har_file_path}' does not exist.")
            return None

        print(f"[*] Parsing network archive file: {har_file_path}...")
        
        with open(har_file_path, 'r', encoding='utf-8') as f:
            try:
                har_data = json.load(f)
            except json.JSONDecodeError:
                print("[Error] Failed to parse file. The input does not match a valid JSON/HAR format.")
                return None

        entries = har_data.get('log', {}).get('entries', [])
        if not entries:
            print("[Warning] No active network traffic data entries were found inside this HAR archive.")
            return None

        # Identify the primary target domain using the initial recorded HTTP request
        first_url = entries[0].get('request', {}).get('url', '')
        base_site_domain = self.extract_domain(first_url)
        
        print(f"[+] Target baseline website detected: {base_site_domain}")
        print(f"[*] Total background network requests captured: {len(entries)}")
        print("-" * 65)

        stats = {
            "First-Party (Essential/Contextual)": 0,
            "Third-Party Tracker (Analytics)": 0,
            "Third-Party Tracker (Advertising)": 0,
            "Third-Party Tracker (Social)": 0,
            "Third-Party (Unclassified/Other CDN)": 0
        }
        
        unique_domains = set()

        for entry in entries:
            request = entry.get('request', {})
            url = request.get('url', '')
            if not url or url.startswith('data:'):
                continue
                
            domain = self.extract_domain(url)
            if not domain:
                continue
                
            unique_domains.add(domain)
            classification = self.classify_domain(domain, base_site_domain)
            
            if classification in stats:
                stats[classification] += 1

        # Display Structured Privacy Auditing Metrics
        print("\n================ DIGITAL PRIVACY METRICS ================")
        for category, count in stats.items():
            print(f" - {category}: {count} request(s)")
            
        total_trackers = (stats["Third-Party Tracker (Analytics)"] + 
                          stats["Third-Party Tracker (Advertising)"] + 
                          stats["Third-Party Tracker (Social)"])
        
        print("-" * 65)
        print(f"UNIQUE NETWORK DOMAINS EVALUATED: {len(unique_domains)}")
        print(f"TOTAL THIRD-PARTY TRACKERS IDENTIFIED: {total_trackers}")
        
        # Calculated privacy metric baseline
        privacy_score = max(0, 100 - (total_trackers * 5))
        print(f"ESTIMATED PRIVACY RESILIENCE SCORE: {privacy_score}/100")
        print("=========================================================\n")
        
        return stats

if __name__ == "__main__":
    # To run a trial, export a network log archive (.har) from your browser DevTools,
    # rename it to 'example.har', and place it in the working directory of this script.
    analyzer = TrackerLensAnalyzer()
    analyzer.analyze_har("example.har")